# Least and greatest waterfall-equilibrium prices

This notebook reproduces the computational examples in *Asset Value and Securitization under Heterogeneous Beliefs*. It also includes a two-tranche multiplicity example and the full-support realized-payoff example from the appendix. The price solver computes only the least equilibrium price $q_{\mathcal T}^{\min}$ and the greatest equilibrium price $q_{\mathcal T}^{\max}$, using the monotone iterations in Proposition 1. It does not search for intermediate equilibria.

In [1]:
from pathlib import Path
import os
import subprocess
import sys

repository_url = (
    "https://github.com/oliverpardo1979/"
    "Asset-value-and-securitization-under-heterogeneous-beliefs-anew.git"
)

if "COLAB_RELEASE_TAG" in os.environ:
    repository_dir = Path("/content/asset-value-securitization")
    if repository_dir.exists():
        subprocess.run(
            ["git", "-C", str(repository_dir), "pull", "--ff-only"],
            check=True,
        )
    else:
        subprocess.run(
            ["git", "clone", "--depth", "1", repository_url, str(repository_dir)],
            check=True,
        )

    subprocess.run(
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            "-q",
            "-r",
            str(repository_dir / "computational_companion" / "requirements.txt"),
        ],
        check=True,
    )
else:
    repository_dir = Path.cwd()
    if repository_dir.name == "computational_companion":
        repository_dir = repository_dir.parent
    if not (repository_dir / "computational_companion").exists():
        raise RuntimeError("Run this notebook from the repository root.")

os.chdir(repository_dir)
print(f"Repository ready at {repository_dir}")

Repository ready at C:\Users\olive\.codex\worktrees\b2cd\Sec Paper


## Define and solve an economy

This first calculation keeps every input visible and editable. The code accepts at most three states and three tranches. The inputs are:

- `dividends`: the current dividend in each state;
- `gross_return`: the gross risk-free return, which must exceed one;
- `theory_A` and `theory_B`: subjective transition matrices, with current states in rows and next-period states in columns; and
- `attachment_points`: the lower endpoint of each tranche. For example, `(0, 2.25)` represents $[0,2.25)$ and $[2.25,\infty)$.

Every row of each transition matrix must contain nonnegative probabilities that sum to one. The values below are illustrative and are not one of the seven paper cases. To explore another parameterization, edit only the input block in the next cell.

In [2]:
import numpy as np

from computational_companion import ExtremeEquilibria, WaterfallEconomy


# INPUTS: edit this block to create another example.
dividends = (0.0, 2.0, 3.0)
gross_return = 2.0

theory_A = np.array(
    (
        (1.0 / 3.0, 1.0 / 3.0, 1.0 / 3.0),
        (1.0 / 3.0, 1.0 / 3.0, 1.0 / 3.0),
        (1.0 / 3.0, 1.0 / 3.0, 1.0 / 3.0),
    )
)
theory_B = np.array(
    (
        (0.90, 0.05, 0.05),
        (0.05, 0.90, 0.05),
        (0.05, 0.05, 0.90),
    )
)

attachment_points = (0.0, 2.25)
state_names = ("l", "m", "h")
theory_names = ("A", "B")

economy = WaterfallEconomy(
    dividends=dividends,
    gross_returns=gross_return,
    theories=(theory_A, theory_B),
    attachment_points=attachment_points,
    state_names=state_names,
    theory_names=theory_names,
)

### 1. Define the price operator

For a candidate continuation-price vector $q$, `tranche_payoffs` computes each tranche's payoff in every next-period state. `price_operator` then evaluates $\Psi_{\mathcal T}(q)$. For each tranche and current state, it uses the theory that assigns the highest expected payoff.

In [3]:
def tranche_payoffs(economy, q):
    prices = np.asarray(q, dtype=float)
    payoffs = np.empty(
        (economy.tranche_count, economy.state_count), dtype=float
    )

    for index, lower_attachment in enumerate(economy.attachment_points):
        payoff = np.maximum(prices - lower_attachment, 0.0)
        if index + 1 < economy.tranche_count:
            upper_attachment = economy.attachment_points[index + 1]
            payoff -= np.maximum(prices - upper_attachment, 0.0)
        payoffs[index] = payoff

    return payoffs

def price_operator(economy, q):
    total_security_value = np.zeros(economy.state_count, dtype=float)

    for payoff in tranche_payoffs(economy, q):
        expected_payoffs = np.einsum(
            "fxy,y->fx", economy.theories, payoff
        )
        total_security_value += expected_payoffs.max(axis=0)

    return (economy.dividends + total_security_value) / economy.gross_returns

### 2. Iterate to a fixed point

Starting from an initial price vector, `iterate_to_fixed_point` repeatedly applies $\Psi_{\mathcal T}$. The lower iteration must be nondecreasing and the upper iteration must be nonincreasing. The function stops only when the change between successive vectors and the fixed-point residual are both below the numerical tolerance.

In [4]:
def iterate_to_fixed_point(
    economy,
    initial_value,
    *,
    increasing,
    absolute_tolerance=1e-12,
    relative_tolerance=1e-12,
    max_iterations=1_000_000,
):
    current = np.asarray(initial_value, dtype=float).copy()

    for iteration in range(1, max_iterations + 1):
        updated = price_operator(economy, current)
        scale = max(1.0, float(np.max(np.abs(updated))))
        tolerance = absolute_tolerance + relative_tolerance * scale

        if increasing and np.any(updated < current - 10 * tolerance):
            raise RuntimeError("the lower iteration ceased to be nondecreasing")
        if not increasing and np.any(updated > current + 10 * tolerance):
            raise RuntimeError("the upper iteration ceased to be nonincreasing")

        step = float(np.max(np.abs(updated - current)))
        current = updated

        if step <= tolerance:
            residual = float(
                np.max(np.abs(price_operator(economy, current) - current))
            )
            if residual <= tolerance:
                return current, iteration, residual

    direction = "lower" if increasing else "upper"
    raise RuntimeError(
        f"the {direction} iteration did not converge after {max_iterations} iterations"
    )

### 3. Compute the least and greatest equilibrium prices

The lower iteration starts from $q^{(0)}=0$ and converges to $q_{\mathcal T}^{\min}$. The upper iteration starts from $M_{\mathcal T}\mathbf 1$ and converges to $q_{\mathcal T}^{\max}$, where

$$M_{\mathcal T}=\frac{\max_x d(x)+a_{\mathcal T}}{\min_x R(x)-1}$$

and $a_{\mathcal T}$ is the attachment point of the unbounded tranche. The code below shows both initial values explicitly.

In [5]:
def compute_extreme_equilibria(
    economy,
    *,
    absolute_tolerance=1e-12,
    relative_tolerance=1e-12,
    max_iterations=1_000_000,
):
    if absolute_tolerance <= 0 or relative_tolerance < 0:
        raise ValueError("tolerances must be positive")
    if max_iterations < 1:
        raise ValueError("max_iterations must be positive")

    q_min, iterations_min, residual_min = iterate_to_fixed_point(
        economy,
        np.zeros(economy.state_count),
        increasing=True,
        absolute_tolerance=absolute_tolerance,
        relative_tolerance=relative_tolerance,
        max_iterations=max_iterations,
    )

    highest_attachment = economy.attachment_points[-1]
    M_T = (economy.dividends.max() + highest_attachment) / (
        economy.gross_returns.min() - 1.0
    )
    q_max, iterations_max, residual_max = iterate_to_fixed_point(
        economy,
        M_T * np.ones(economy.state_count),
        increasing=False,
        absolute_tolerance=absolute_tolerance,
        relative_tolerance=relative_tolerance,
        max_iterations=max_iterations,
    )

    ordering_tolerance = 10 * (
        absolute_tolerance
        + relative_tolerance * max(1.0, np.max(np.abs(q_max)))
    )
    if np.any(q_min > q_max + ordering_tolerance):
        raise RuntimeError("the computed lower bound exceeds the upper bound")

    return ExtremeEquilibria(
        q_min=q_min,
        q_max=q_max,
        iterations_min=iterations_min,
        iterations_max=iterations_max,
        residual_min=residual_min,
        residual_max=residual_max,
    )

### 4. Run the example

Distinct values of $q_{\mathcal T}^{\min}$ and $q_{\mathcal T}^{\max}$ establish multiplicity. Coincident values provide numerical evidence of uniqueness.

In [6]:
extreme_equilibria = compute_extreme_equilibria(economy)

print("q_min =", np.round(extreme_equilibria.q_min, 3))
print("q_max =", np.round(extreme_equilibria.q_max, 3))
print("Multiplicity detected:", extreme_equilibria.multiplicity_detected())
print(
    "Maximum fixed-point residual:",
    f"{max(extreme_equilibria.residual_min, extreme_equilibria.residual_max):.2e}",
)

q_min = [1.005 2.154 2.871]
q_max = [1.005 2.154 2.871]
Multiplicity detected: False
Maximum fixed-point residual: 1.67e-12


## Reproduce the paper examples

The seven cases below compare the no-tranching and tranching versions of the motivating example, an additional two-tranche multiplicity case, Example 1 of the paper, and the full-support realized-payoff example. The tranching in Example 1 uses only senior debt $[0,3)$ and residual equity $[3,\infty)$.

The function `all_examples()` loads the seven parameterizations stored with the code. To display every input for one of them, change `selected_example_number` in the next cell to an integer from 1 to 7.

In [7]:
from computational_companion.paper_examples import all_examples

paper_examples = all_examples()
for number, example in enumerate(paper_examples, start=1):
    print(f"{number}. {example.name}")

selected_example_number = 1  # Change this number to inspect another case.
selected_example = paper_examples[selected_example_number - 1]
selected_economy = selected_example.economy

print(f"\nInputs for: {selected_example.name}")
print("Dividends:", selected_economy.dividends)
print("Gross returns:", selected_economy.gross_returns)
print("Attachment points:", selected_economy.attachment_points)
for theory_name, transition_matrix in zip(
    selected_economy.theory_names, selected_economy.theories
):
    print(f"Theory {theory_name}:")
    print(transition_matrix)

1. Motivating example: no tranching
2. Motivating example: two tranches
3. Motivating family: two-tranche multiplicity
4. Example 1: no tranching
5. Example 1: two-tranche debt-equity structure
6. Realized-payoff example: no tranching
7. Realized-payoff example: three tranches

Inputs for: Motivating example: no tranching
Dividends: [0. 2. 3.]
Gross returns: [2. 2. 2.]
Attachment points: [0.]
Theory A:
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
Theory B:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
from IPython.display import Markdown, display


def format_vector(values):
    return "(" + ", ".join(f"{value:.3f}" for value in values) + ")"


rows = []
for example in paper_examples:
    result = compute_extreme_equilibria(example.economy)
    rows.append(
        (
            example.name,
            format_vector(result.q_min),
            format_vector(result.q_max),
            "Yes" if result.multiplicity_detected() else "No",
            max(result.residual_min, result.residual_max),
        )
    )

table = [
    r"| Case | $q^{\min}$ | $q^{\max}$ | Multiplicity | Maximum residual |",
    "| --- | --- | --- | --- | --- |",
]
table.extend(
    f"| {name} | {q_min} | {q_max} | {multiple} | {residual:.2e} |"
    for name, q_min, q_max, multiple, residual in rows
)
display(Markdown("\n".join(table)))

| Case | $q^{\min}$ | $q^{\max}$ | Multiplicity | Maximum residual |
| --- | --- | --- | --- | --- |
| Motivating example: no tranching | (1.000, 2.000, 3.000) | (1.000, 2.000, 3.000) | No | 1.82e-12 |
| Motivating example: two tranches | (1.050, 2.250, 3.000) | (1.050, 2.250, 3.000) | No | 1.25e-12 |
| Motivating family: two-tranche multiplicity | (46.634, 48.539, 51.724) | (48.497, 51.077, 53.191) | Yes | 4.81e-11 |
| Example 1: no tranching | (2.593, 2.844, 2.991) | (2.593, 2.844, 2.991) | No | 3.64e-12 |
| Example 1: two-tranche debt-equity structure | (2.593, 2.844, 2.991) | (2.741, 3.020, 3.142) | Yes | 3.64e-12 |
| Realized-payoff example: no tranching | (1.994, 2.500, 4.000) | (1.994, 2.500, 4.000) | No | 9.80e-13 |
| Realized-payoff example: three tranches | (2.000, 2.500, 4.000) | (2.000, 2.500, 4.000) | No | 6.37e-13 |

## Full-support realized-payoff example

This example uses the three theories and full-support objective transition matrix reported in the appendix. The benchmark has no tranching. The securitized economy has attachment points $(0,2,5/2)$.

The calculation below first obtains the least and greatest price vectors. It then applies the fixed priority ordering $\mathcal A\succ\mathcal B\succ\mathcal C$ whenever theories tie, identifies the selected buyer of every tranche in every state, and computes each theory's long-run realized excess payoff under the objective transition matrix.

The code keeps this payoff calculation visible because it is separate from the reusable price solver.

In [9]:
from computational_companion.paper_examples import (
    REALIZED_PAYOFF_EXPECTED_DELTAS,
    REALIZED_PAYOFF_OBJECTIVE_TRANSITION,
    REALIZED_PAYOFF_PRIORITY,
    REALIZED_PAYOFF_STATIONARY_DISTRIBUTION,
    realized_payoff_example,
)


def selected_buyers_and_realized_excess_payoffs(economy, q):
    payoffs = tranche_payoffs(economy, q)
    perceived_payoffs = np.einsum(
        "fxy,ty->tfx", economy.theories, payoffs
    )
    objective_payoffs = np.einsum(
        "xy,ty->tx", REALIZED_PAYOFF_OBJECTIVE_TRANSITION, payoffs
    )

    buyers = np.empty(
        (economy.tranche_count, economy.state_count), dtype=int
    )
    for tranche_index in range(economy.tranche_count):
        for state_index in range(economy.state_count):
            values = perceived_payoffs[tranche_index, :, state_index]
            highest_value = values.max()
            maximizing_theories = np.isclose(
                values, highest_value, atol=1e-10, rtol=0.0
            )
            buyers[tranche_index, state_index] = next(
                theory_index
                for theory_index in REALIZED_PAYOFF_PRIORITY
                if maximizing_theories[theory_index]
            )

    deltas = np.zeros(len(economy.theory_names))
    for tranche_index in range(economy.tranche_count):
        for state_index, state_weight in enumerate(
            REALIZED_PAYOFF_STATIONARY_DISTRIBUTION
        ):
            buyer = buyers[tranche_index, state_index]
            deltas[buyer] += state_weight * (
                objective_payoffs[tranche_index, state_index]
                - perceived_payoffs[tranche_index, buyer, state_index]
            )

    return buyers, deltas


payoff_rows = []
payoff_results = {}
for with_tranching in (False, True):
    example = realized_payoff_example(with_tranching=with_tranching)
    result = compute_extreme_equilibria(example.economy)
    buyers, deltas = selected_buyers_and_realized_excess_payoffs(
        example.economy, result.q_min
    )
    payoff_results[with_tranching] = (example, result, buyers, deltas)

    np.testing.assert_allclose(
        deltas,
        REALIZED_PAYOFF_EXPECTED_DELTAS[with_tranching],
        atol=2e-10,
        rtol=0.0,
    )
    payoff_rows.append(
        (
            example.name,
            format_vector(result.q_min),
            *(f"{value:.6f}" for value in deltas),
            f"{deltas.sum():.6f}",
        )
    )

payoff_table = [
    r"| Case | $q^{\min}$ | $\Delta_A$ | $\Delta_B$ | $\Delta_C$ | Aggregate |",
    "| --- | --- | ---: | ---: | ---: | ---: |",
]
payoff_table.extend(
    f"| {name} | {q_min} | {delta_a} | {delta_b} | {delta_c} | {aggregate} |"
    for name, q_min, delta_a, delta_b, delta_c, aggregate in payoff_rows
)
display(Markdown("\n".join(payoff_table)))

tranching_example, _, tranching_buyers, _ = payoff_results[True]
buyer_names = np.asarray(tranching_example.economy.theory_names)[
    tranching_buyers
]
buyer_table = [
    "| Tranche | l | m | h |",
    "| --- | --- | --- | --- |",
]
for tranche_name, state_buyers in zip(
    ("Senior", "Mezzanine", "Junior"), buyer_names
):
    buyer_table.append(
        f"| {tranche_name} | " + " | ".join(state_buyers) + " |"
    )
display(Markdown("\n".join(buyer_table)))

| Case | $q^{\min}$ | $\Delta_A$ | $\Delta_B$ | $\Delta_C$ | Aggregate |
| --- | --- | ---: | ---: | ---: | ---: |
| Realized-payoff example: no tranching | (1.994, 2.500, 4.000) | 0.000000 | -0.083557 | 0.000000 | -0.083557 |
| Realized-payoff example: three tranches | (2.000, 2.500, 4.000) | 0.000000 | -0.062500 | -0.027778 | -0.090278 |

| Tranche | l | m | h |
| --- | --- | --- | --- |
| Senior | A | A | A |
| Mezzanine | C | A | A |
| Junior | B | A | A |

The computation confirms the comparison in the appendix:

$$
\Delta_{\mathcal B}^{\mathcal T^1}=-\frac{1}{16}
>
-\frac{373}{4464}
=\Delta_{\mathcal B}^{\mathcal T^0}.
$$

Theory $\mathcal C$ buys the mezzanine tranche at state $l$, and its realized excess payoff falls from zero to $-1/36$. Theory $\mathcal B$ buys the junior tranche at that state and its loss becomes smaller. The aggregate excess payoff nevertheless falls, from $-373/4464$ to $-13/144$, as required by the aggregate-payoff proposition.

## Two-tranche multiplicity within the motivating family

The additional parameterization retains the two theories used in the motivating example: theory $\mathcal A$ assigns probability $1/3$ to every next-period state, while theory $\mathcal B$ assigns probability $9/10$ to the current state and $1/20$ to each other state. Set

$$R=\frac{21}{20},\qquad d=(0,2,3),\qquad \mathcal T=\{[0,51),[51,\infty)\}.$$

The two monotone iterations yield

$$q_{\mathcal T}^{\min}=\left(\frac{28400}{609},\frac{29560}{609},\frac{1500}{29}\right)\approx(46.634,48.539,51.724),$$

$$q_{\mathcal T}^{\max}=\frac{1}{3187}(154560,162783,169521)\approx(48.497,51.077,53.191).$$

At the least equilibrium, the junior tranche pays only in state $h$. At the greatest equilibrium, it pays in states $m$ and $h$. In state $m$, both tranches are priced by theory $\mathcal A$ at the least equilibrium, whereas theory $\mathcal B$ prices the senior tranche and theory $\mathcal A$ prices the junior tranche at the greatest equilibrium. Thus, two tranches are sufficient for multiple equilibrium prices.

## Verification

The first check verifies that the visible notebook algorithm produces the same extreme equilibria as the reusable implementation in `waterfall_equilibria.py`. The regression tests then compare the computed equilibria with all values reported in the paper. They also verify the intermediate price vector in Example 1 and independently recompute the selected buyers and realized excess payoffs in the full-support example.

In [10]:
from computational_companion import (
    compute_extreme_equilibria as package_compute_extreme_equilibria,
)

for example in paper_examples:
    visible_result = compute_extreme_equilibria(example.economy)
    package_result = package_compute_extreme_equilibria(example.economy)
    np.testing.assert_allclose(visible_result.q_min, package_result.q_min)
    np.testing.assert_allclose(visible_result.q_max, package_result.q_max)

print("Visible algorithm matches the reusable implementation.")

subprocess.run(
    [
        sys.executable,
        "-m",
        "unittest",
        "computational_companion.test_waterfall_equilibria",
    ],
    cwd=repository_dir,
    check=True,
)

Visible algorithm matches the reusable implementation.


CompletedProcess(args=['C:\\Users\\olive\\.cache\\codex-runtimes\\codex-primary-runtime\\dependencies\\python\\python.exe', '-m', 'unittest', 'computational_companion.test_waterfall_equilibria'], returncode=0)